version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app

jobs:
  "node-4":
    <<: *defaults
    docker:
      - image: cypress/base:4
    steps:
      - run: npm install cypress@$CYPRESS_TAG
      - run: DEBUG=cypress:cli $(npm bin)/cypress verify

  "node-6":
    <<: *defaults
    docker:
      - image: cypress/base:6
    steps:
      - run: npm install cypress@$CYPRESS_TAG
      - run: DEBUG=cypress:cli $(npm bin)/cypress verify

  "node-8":
    <<: *defaults
    docker:
      - image: cypress/base:8
        user: node
    steps:
      - run: npm init -y
      - run: npm install cypress@$CYPRESS_TAG
      - run: DEBUG=cypress:cli $(npm bin)/cypress verify

  "node-8-global":
    <<: *defaults
    docker:
      - image: cypress/base:8
    steps:
      - run: npm install -g cypress@$CYPRESS_TAG
      - run: DEBUG=cypress:cli cypress verify
      - run: git clone https://github.com/bahmutov/foo-page.git
      - run: cd foo-page && cypress run

  "node-8-global-kitchen-sink":
    <<: *defaults
    docker:
      - image: cypress/base:8
    steps:
      - run: npm install -g cypress@$CYPRESS_TAG
      - run: DEBUG=cypress:cli cypress verify
      - run: git clone https://github.com/cypress-io/cypress-example-kitchensink.git
      - run:
          name: Test Kitchensink example
          command: |
            cd cypress-example-kitchensink
            git checkout 0.20.0
            cypress run

workflows:
  version: 2
  test-cypress-installs:
    jobs:
      - node-4
      - node-6
      - node-8
      - node-8-global
      - node-8-global-kitchen-sink
