version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
      - image: cypress/base

jobs:
  "node-0.12":
    <<: *defaults
    steps:
      - run: nvm install 0.12
      - run: npm install cypress@$CYPRESS_TAG
      - run: $(npm bin)/cypress verify

  "node-4":
    <<: *defaults
    steps:
      - run: nvm install 4
      - run: npm install cypress@$CYPRESS_TAG
      - run: $(npm bin)/cypress verify

  "node-6":
    <<: *defaults
    steps:
      - run: nvm install 6
      - run: npm install cypress@$CYPRESS_TAG
      - run: $(npm bin)/cypress verify

  "node-8":
    <<: *defaults
    steps:
      - run: nvm install 8
      - run: npm install cypress@$CYPRESS_TAG
      - run: $(npm bin)/cypress verify

workflows:
  version: 2
  test-cypress-installs:
    jobs:
      - node-0.12
      - node-4
      - node-6
      - node-8
