version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app

jobs:
  "node-4":
    <<: *defaults
    docker:
      - image: cypress/base:4
    steps:
      - run: echo install $CYPRESS_NPM_PACKAGE_NAME
      - run: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run: $(npm bin)/cypress version
      - run: DEBUG=cypress:cli $(npm bin)/cypress verify

  "node-6":
    <<: *defaults
    docker:
      - image: cypress/base:6
    steps:
      - run: echo install $CYPRESS_NPM_PACKAGE_NAME
      - run: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run: $(npm bin)/cypress version
      - run: DEBUG=cypress:cli $(npm bin)/cypress verify

  "node-8":
    <<: *defaults
    docker:
      - image: cypress/base:8
        user: node
    steps:
      - run: npm init -y
      - run: echo install $CYPRESS_NPM_PACKAGE_NAME
      - run: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run: $(npm bin)/cypress version
      - run: DEBUG=cypress:cli $(npm bin)/cypress verify

  "node-8-global":
    <<: *defaults
    docker:
      - image: cypress/base:8
    steps:
      - run: echo install $CYPRESS_NPM_PACKAGE_NAME
      - run: npm install -g $CYPRESS_NPM_PACKAGE_NAME
      - run: DEBUG=cypress:cli cypress verify
      - run: git clone https://github.com/cypress-io/cypress-test-tiny.git
      - run:
          command: cypress run
          working_directory: cypress-test-tiny

  "yarn":
    <<: *defaults
    docker:
      - image: cypress/base:8
    steps:
      - run: npm install -g yarn
      - run: git clone https://github.com/cypress-io/cypress-test-tiny.git
      - run:
          name: Install Cypress with Yarn
          working_directory: cypress-test-tiny
          command: |
            echo install $CYPRESS_NPM_PACKAGE_NAME
            yarn add -D $CYPRESS_NPM_PACKAGE_NAME
      - run:
          command: $(npm bin)/cypress version
          working_directory: cypress-test-tiny
      - run:
          command: $(npm bin)/cypress verify
          working_directory: cypress-test-tiny
      - run:
          command: $(npm bin)/cypress run
          working_directory: cypress-test-tiny

  "yarn-1.1":
    <<: *defaults
    docker:
      - image: node:8.6
    steps:
      - run: npm install -g yarn@1.1.0
      - run: git clone https://github.com/cypress-io/cypress-test-tiny.git
      - run:
          name: Install Cypress with Yarn 1.1.0
          working_directory: cypress-test-tiny
          command: |
            echo Installing Cypress from $CYPRESS_NPM_PACKAGE_NAME
            yarn add -D $CYPRESS_NPM_PACKAGE_NAME
      - run:
          command: $(npm bin)/cypress version
          working_directory: cypress-test-tiny

  "yarn-1.1-cypress-0.20.3":
    <<: *defaults
    docker:
      - image: node:8.6
    steps:
      - run: npm install -g yarn@1.1.0
      - run: git clone https://github.com/cypress-io/cypress-test-tiny.git
      - run:
          name: Install Cypress with Yarn 1.1.0
          working_directory: cypress-test-tiny
          command: yarn add -D cypress@0.20.3
      - run:
          command: $(npm bin)/cypress version
          working_directory: cypress-test-tiny

  "node-8-global-kitchen-sink":
    <<: *defaults
    docker:
      - image: cypress/base:8
    steps:
      - run: echo install $CYPRESS_NPM_PACKAGE_NAME
      - run: npm install -g $CYPRESS_NPM_PACKAGE_NAME
      - run: DEBUG=cypress:cli cypress verify
      - run: git clone https://github.com/cypress-io/cypress-example-kitchensink.git
      - run:
          name: Install Kitchensink deps (but only the server)
          working_directory: cypress-example-kitchensink
          command: |
            git checkout 0.20.0
            npm install --production
      - run:
          name: Start Kitchensink example server
          command: npm start
          working_directory: cypress-example-kitchensink
          background: true
      - run:
          name: Running tests against Kitchensink example
          command: cypress run
          working_directory: cypress-example-kitchensink

workflows:
  version: 2
  test-cypress-installs:
    jobs:
      - node-4
      - node-6
      - node-8
      - node-8-global
      - node-8-global-kitchen-sink
      - yarn
      - yarn-1.1
      - yarn-1.1-cypress-0.20.3
