version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app

jobs:
  "node-0.12":
    <<: *defaults
    docker:
      - image: node:0.12
    steps:
      - run: npm install cypress@$CYPRESS_TAG
      - run: $(npm bin)/cypress verify

  "node-4":
    <<: *defaults
    docker:
      - image: node:4
    steps:
      - run: npm install cypress@$CYPRESS_TAG
      - run: $(npm bin)/cypress verify

  "node-6":
    <<: *defaults
    docker:
      - image: node:6
    steps:
      - run: npm install cypress@$CYPRESS_TAG
      - run: $(npm bin)/cypress verify

  "node-8":
    <<: *defaults
    docker:
      - image: node:8
    steps:
      - run: npm install cypress@$CYPRESS_TAG
      - run: $(npm bin)/cypress verify

workflows:
  version: 2
  test-cypress-installs:
    jobs:
      - node-0.12
      - node-4
      - node-6
      - node-8
